<a href="https://colab.research.google.com/github/fujita022/CP2-2Semestre-WebDev/blob/main/Pandas_estudo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
pd.read_csv(url)

      Tipo;Bairro;Quartos;Vagas;Suites;Area;Valor;Condominio;IPTU
0              Quitinete;Copacabana;1;0;0;40;1700;500;60
1                  Casa;Jardim Botânico;2;0;1;100;7000;;
2      Conjunto Comercial/Sala;Barra da Tijuca;0;4;0;...
3                 Apartamento;Centro;1;0;0;15;800;390;20
4             Apartamento;Higienópolis;1;0;0;48;800;230;
...                                                  ...
32955               Quitinete;Centro;0;0;0;27;800;350;25
32956       Apartamento;Jacarepaguá;3;1;2;78;1800;800;40
32957  Apartamento;São Francisco Xavier;2;1;0;48;1400...
32958              Apartamento;Leblon;2;0;0;70;3000;760;
32959  Conjunto Comercial/Sala;Centro;0;0;0;250;6500;...

[32960 rows x 1 columns]

Warning: total number of rows (32960) exceeds max_rows (20000). Limiting to first (20000) rows.

In [3]:
pd.read_csv(url, sep= ';')

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [4]:
dados = pd.read_csv(url, sep= ';')
dados

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [5]:
dados.head()

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN

In [6]:
dados.tail(10)

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
32950,Apartamento,Tijuca,1,0,0,28,1000.0,360.0,25.0
32951,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
32952,Casa de Condomínio,Barra da Tijuca,5,3,4,450,15000.0,1711.0,2332.0
32953,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
32954,Box/Garagem,Centro,0,0,0,755,14000.0,NaN,NaN
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [7]:
type(dados)

pandas.core.frame.DataFrame

In [8]:
dados.shape

(32960, 9)

In [9]:
dados[['IPTU']]

         IPTU
0        60.0
1         NaN
2      1111.0
3        20.0
4         NaN
...       ...
32955    25.0
32956    40.0
32957    37.0
32958     NaN
32959  1109.0

[32960 rows x 1 columns]

In [11]:
dados[['IPTU','Valor']]

         IPTU   Valor
0        60.0  1700.0
1         NaN  7000.0
2      1111.0  5200.0
3        20.0   800.0
4         NaN   800.0
...       ...     ...
32955    25.0   800.0
32956    40.0  1800.0
32957    37.0  1400.0
32958     NaN  3000.0
32959  1109.0  6500.0

[32960 rows x 2 columns]

In [15]:
url = ('https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/desafios/alunos.csv')
pd.read_csv(url)

alunos = pd.read_csv(url)
alunos

         Nome  Idade  Notas  Aprovado
0         Ary     20    7.5      True
1         Ana     18    NaN     False
2       Cátia     27    2.5     False
3       Denis     18    5.0     False
4        Beto     21   10.0      True
5       Bruna     23    NaN     False
6        Dara     21    7.0      True
7      Carlos     19    6.0      True
8       Alice     35    5.6     False
9       Vitor     28    NaN     False
10     Daniel     21    NaN     False
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [16]:
alunos.head(7)

    Nome  Idade  Notas  Aprovado
0    Ary     20    7.5      True
1    Ana     18    NaN     False
2  Cátia     27    2.5     False
3  Denis     18    5.0     False
4   Beto     21   10.0      True
5  Bruna     23    NaN     False
6   Dara     21    7.0      True

In [17]:
alunos.tail(7)

         Nome  Idade  Notas  Aprovado
11       Igor     24    4.5     False
12  Sthefanie     26    9.5      True
13      Mirla     25    9.0      True
14      Paulo     37    NaN     False
15     Mylena     29    7.0      True
16      Lucas     33    NaN     False
17      Nadia     34    8.0      True

In [21]:
alunos.shape

(18, 4)

In [23]:
alunos.columns

Index(['Nome', 'Idade', 'Notas', 'Aprovado'], dtype='object')

In [25]:
alunos['Nome']

0           Ary
1           Ana
2         Cátia
3         Denis
4          Beto
5         Bruna
6          Dara
7        Carlos
8         Alice
9         Vitor
10       Daniel
11         Igor
12    Sthefanie
13        Mirla
14        Paulo
15       Mylena
16        Lucas
17        Nadia
Name: Nome, dtype: object

In [27]:
alunos.dtypes

Nome         object
Idade         int64
Notas       float64
Aprovado       bool
dtype: object

In [29]:
alunos[['Nome','Notas']]

         Nome  Notas
0         Ary    7.5
1         Ana    NaN
2       Cátia    2.5
3       Denis    5.0
4        Beto   10.0
5       Bruna    NaN
6        Dara    7.0
7      Carlos    6.0
8       Alice    5.6
9       Vitor    NaN
10     Daniel    NaN
11       Igor    4.5
12  Sthefanie    9.5
13      Mirla    9.0
14      Paulo    NaN
15     Mylena    7.0
16      Lucas    NaN
17      Nadia    8.0

In [31]:
alunos.describe()

           Idade      Notas
count  18.000000  12.000000
mean   25.500000   6.800000
std     6.070662   2.204953
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000